title = "Deployment for example server"

[ssh]
username = "foo"
password = "bar"
identityfile = "/some/file"

[envvars]
OTEL_SERVICE_NAME = "Gorun"

[[servers]]
hostname = "some-server-A"

[[servers]]
hostname = "some-server-B"

[[tasks]]
name = "create group docker"
cmd = "group add docker"

    [[tasks.tasks]]
    name = "verify group exists"
    cmd = "echo 'some verification command'"

[[tasks]]
name = "create user foo"
cmd = "useradd foo"

    [[tasks.tasks]]
    name = "echo running some check"

    [[tasks.tasks]]
    name = "add user to docker group"
    cmd = "usermod -Ga docker foo"

        [[tasks.tasks.tasks]]
        name = "echo date"
        cmd = "date"

[[tasks.servers]]
hostname = "localhost"

[[tasks.servers]]
hostname = "some-server-B"
