package parser

import (
	"fmt"
	"strconv"
	"unicode"
)

// Lexer holds the state of the scanner.
type Lexer struct {
	input  []rune // The source code broken into characters
	pos    int    // Current position in the input
	result int    // Holds the final calculation result
}

// NewLexer initializes a new lexer instance.
func NewLexer(input string) *Lexer {
	return &Lexer{input: []rune(input)}
}

// Lex is called by the generated yyParse to get the next token.
// It must return the token type ID (e.g., NUMBER, '+') or 0 for EOF.
func (l *Lexer) Lex(lval *yySymType) int {
	// Skip whitespace
	for l.pos < len(l.input) && unicode.IsSpace(l.input[l.pos]) {
		l.pos++
	}

	// Check for End of File (EOF)
	if l.pos >= len(l.input) {
		return 0
	}

	ch := l.input[l.pos]

	// Handle Numbers
	if unicode.IsDigit(ch) {
		start := l.pos
		for l.pos < len(l.input) && unicode.IsDigit(l.input[l.pos]) {
			l.pos++
		}
		// Extract the full number string
		numStr := string(l.input[start:l.pos])
		val, _ := strconv.Atoi(numStr)

		// Pass the value to the parser via lval (defined by %union)
		lval.num = val
		return NUMBER // This constant is generated by goyacc
	}

	// Handle Operators (+, -, *, /)
	l.pos++
	return int(ch) // Return the single character character literal as its own ID
}

// Error is called by yyParse when a syntax error is encountered.
func (l *Lexer) Error(s string) {
	fmt.Printf("Syntax Error: %s at character position %d\n", s, l.pos)
}
